name: Build deb package with Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and deploy
      run: ./build.sh

    - name: Archive artifacs
      uses: actions/upload-artifact@v2
      with:
        name: emacs-gcc-pgtk
        path: ./deploy/emacs-gcc-pgtk_*.deb
        
    - name: Create repository
      uses: jrandiny/apt-repo-action@v1
      with:
        github_token: ${{ secrets.PAT }}
        arch: |
          amd64
          i386
        version: |
          bookworm
          testing
        file: ./deploy/emacs-gcc-pgtk_*.deb
        file_target_version: testing
        public_key: ${{ secrets.PUBLIC }}
        private_key: ${{ secrets.PRIVATE }}
        key_passphrase: ${{ secrets.SECRET }}
